const PRODUCTCATALOGUE = [
    {
        product_id: 9238475482093475,
        companyName: 'Athletic Gear Co.',
        productName: 'Athletic Sneakers - FlexStride',
        summary: 'Versatile athletic sneakers for all kinds of activities',
        description: 'Experience the comfort and flexibility of the FlexStride athletic sneakers. Whether you are hitting the gym, going for a run, or just enjoying a casual stroll, these sneakers offer the perfect combination of style and performance. The breathable mesh upper keeps your feet cool, while the cushioned sole provides excellent support for every step.',
        price: '$74.99',
        discountRate: '15%',
        oldPrice: '$89.99',
        src: './images/shoes/images_1.jpeg',
        collection: 'Men',
        category: 'Athletic'
    },
    {
        product_id: 3847560284573628,
        companyName: 'Fashion Avenue',
        productName: 'Casual Slip-On Shoes - ComfortEase',
        summary: 'Stylish and comfortable slip-on shoes for everyday wear',
        description: 'Upgrade your casual wardrobe with the ComfortEase slip-on shoes. These shoes combine style and comfort effortlessly. The minimalist design pairs well with any outfit, and the cushioned insole ensures all-day comfort. Whether you are heading to work or meeting friends, these slip-on shoes are a versatile choice.',
        price: '$59.99',
        discountRate: '10%',
        oldPrice: '$66.99',
        src: './images/shoes/puma-clyde-OG-sneakers.webp',
        collection: 'Unisex',
        category: 'Casual'
    },
    {
        product_id: 1938572048503948,
        companyName: 'Elite Sports',
        productName: 'Soccer Cleats - PrecisionStrike',
        summary: 'High-performance soccer cleats for precision and control',
        description: 'Dominate the field with the PrecisionStrike soccer cleats. Designed for players who demand precision, these cleats feature advanced traction patterns for quick cuts and precise movements. The lightweight construction and responsive cushioning ensure you stay comfortable and agile throughout the match.',
        price: '$99.95',
        discountRate: '20%',
        oldPrice: '$124.99',
        src: './images/shoes/images_2.jpeg',
        collection: 'Men',
        category: 'Sport'
    },
    {
        product_id: 5729837604950398,
        companyName: 'Fashion Forward',
        productName: 'High Heel Pumps - Elegance',
        summary: 'Elegant high heel pumps for formal occasions',
        description: 'Step into elegance with the Elegance high heel pumps. Whether you are attending a formal event or a special occasion, these pumps add a touch of sophistication to your ensemble. The classic design and comfortable heel height make them a timeless choice for any fashion-forward woman.',
        price: '$79.99',
        discountRate: '10%',
        oldPrice: '$89.99',
        src: './images/shoes/kayss.png',
        collection: 'Women',
        category: 'Fashion'
    },
    {
        product_id: 4837260275839205,
        companyName: 'Adventure Gear',
        productName: 'Hiking Boots - TrekMaster',
        summary: 'Durable hiking boots for outdoor adventures',
        description: 'Embark on your next outdoor adventure with confidence in the TrekMaster hiking boots. These boots are built to withstand rugged terrains and provide excellent ankle support. The waterproof construction keeps your feet dry, while the aggressive outsole offers exceptional traction on various surfaces.',
        price: '$129.99',
        discountRate: '0%',
        oldPrice: '$129.99',
        src: './images/shoes/new-balance-990v6.webp',
        collection: 'Unisex',
        category: 'Outdoor'
    },
    {
        product_id: 6398475602837502,
        companyName: 'Active Lifestyle',
        productName: 'Running Shoes - SpeedRush',
        summary: 'Lightweight running shoes for a speedy performance',
        description: 'Experience the thrill of speed with the SpeedRush running shoes. Designed for runners seeking lightweight and responsive footwear, these shoes feature a sleek design and breathable upper. The cushioned midsole absorbs impact, while the flexible outsole promotes a natural stride.',
        price: '$89.95',
        discountRate: '15%',
        oldPrice: '$104.99',
        src: './images/shoes/images_2.jpeg',
        collection: 'Unisex',
        category: 'Sport'
    },
    {
        product_id: 9485730287503947,
        companyName: 'Casual Vibes',
        productName: 'Slip-On Sandals - Coastal Comfort',
        summary: 'Casual slip-on sandals for beach days and relaxation',
        description: 'Enjoy the comfort of the Coastal Comfort slip-on sandals on your next beach vacation or leisure day. These sandals feature a laid-back design with a cushioned footbed for a relaxed feel. The slip-on style makes them convenient to wear, and the durable sole is ready for sandy shores and beyond.',
        price: '$34.99',
        discountRate: '0%',
        oldPrice: '$34.99',
        src: './images/shoes/images_15.jpeg',
        collection: 'Unisex',
        category: 'Casual'
    },
    {
        product_id: 2938405768230497,
        companyName: 'Trendy Steps',
        productName: 'Platform Sneakers - Urban Chic',
        summary: 'Fashionable platform sneakers for a trendy look',
        description: 'Elevate your street style with the Urban Chic platform sneakers. These sneakers combine a classic silhouette with a modern twist – a platform sole. Whether you pair them with jeans or a skirt, these sneakers add a touch of urban chic to your outfit.',
        price: '$59.99',
        discountRate: '10%',
        oldPrice: '$66.99',
        src: './images/shoes/zannoti.jpg',
        collection: 'Women',
        category: 'Fashion'
    },
    {
        product_id: 7502938465283750,
        companyName: 'Active Gear Pro',
        productName: 'Crossfit Shoes - PowerLift',
        summary: 'Crossfit shoes for lifting and high-intensity workouts',
        description: 'Conquer your crossfit workouts with the PowerLift crossfit shoes. These shoes are designed to provide stability and support during heavy lifts and dynamic movements. The flat and stable sole ensures a solid base for squats, deadlifts, and more. Stay comfortable and focused during your intense training sessions.',
        price: '$89.99',
        discountRate: '0%',
        oldPrice: '$89.99',
        src: './images/shoes/images_3.jpeg',
        collection: 'Unisex',
        category: 'Sport'
    },
    {
        product_id: 2093485760293857,
        companyName: 'Classic Elegance',
        productName: 'Loafers - Timeless Charm',
        summary: 'Classic loafers for a touch of timeless charm',
        description: 'Embrace classic style with the Timeless Charm loafers. These loafers feature a refined design that pairs well with both casual and semi-formal outfits. The slip-on style and comfortable fit make them an essential addition to your footwear collection.',
        price: '$49.95',
        discountRate: '20%',
        oldPrice: '$62.99',
        src: './images/shoes/images_7.jpeg',
        collection: 'Unisex',
        category: 'Casual'
    },
    {
        product_id: 2039485729408573,
        companyName: 'Runners Haven',
        productName: 'Trail Running Shoes - TerrainTrek',
        summary: 'Durable trail running shoes for off-road adventures',
        description: 'Conquer rough terrains with confidence in the TerrainTrek trail running shoes. These shoes are built to handle the challenges of off-road running, with rugged traction and protective features. The cushioned midsole offers comfort during long runs, while the breathable upper keeps your feet cool.',
        price: '$89.99',
        discountRate: '10%',
        oldPrice: '$99.99',
        src: './images/shoes/images_5.jpeg',
        collection: 'Unisex',
        category: 'Sport'
    },
    {
        product_id: 7058203948572048,
        companyName: 'FashionFusion',
        productName: 'Platform Sandals - Boho Bliss',
        summary: 'Bohemian-style platform sandals for a laid-back look',
        description: "Channel boho vibes with the Boho Bliss platform sandals. These sandals feature a platform sole and intricate woven details, perfect for adding a touch of free-spirited style to your outfit. Whether you're strolling through a festival or enjoying a summer day, these sandals are the epitome of relaxed chic.",
        price: '$54.99',
        discountRate: '0%',
        oldPrice: '$54.99',
        src: './images/shoes/seeker.png',
        collection: 'Women',
        category: 'Fashion'
    },
    {
        product_id: 9203748592037485,
        companyName: 'Outdoor Explorers',
        productName: 'Hiking Sandals - AdventurePro',
        summary: 'Versatile hiking sandals for outdoor enthusiasts',
        description: "Embrace the versatility of the AdventurePro hiking sandals. Whether you're hiking through streams, exploring rocky terrain, or simply enjoying a walk in the woods, these sandals provide the grip and protection you need. The adjustable straps ensure a secure fit, and the cushioned footbed keeps you comfortable on your journey.",
        price: '$69.95',
        discountRate: '15%',
        oldPrice: '$82.99',
        src: './images/shoes/images_18.jpeg',
        collection: 'Unisex',
        category: 'Outdoor'
    },
    {
        product_id: 6394850293572048,
        companyName: 'Active Performance',
        productName: 'Basketball Shoes - SlamDunk Pro',
        summary: 'High-performance basketball shoes for court domination',
        description: "Elevate your game with the SlamDunk Pro basketball shoes. Designed for agility, these shoes feature responsive cushioning and advanced traction patterns to help you make quick moves on the court. The ankle support and lockdown fit provide stability, ensuring you're ready to slam dunk your way to victory.",
        price: '$109.99',
        discountRate: '0%',
        oldPrice: '$109.99',
        src: './images/shoes/images_11.jpeg',
        collection: 'Men',
        category: 'Sport'
    },
    {
        product_id: 8203948572037485,
        companyName: 'Elegant Attire',
        productName: 'Stiletto Heels - GlamourGlow',
        summary: 'Glamorous stiletto heels for special occasions',
        description: 'Step into the spotlight with the GlamourGlow stiletto heels. These heels exude elegance and sophistication, making them the perfect choice for weddings, parties, and formal events. The sleek design and high heel height add a touch of glamour to any ensemble.',
        price: '$89.99',
        discountRate: '10%',
        oldPrice: '$99.99',
        src: './images/shoes/rainbow-club-clara.jpg',
        collection: 'Women',
        category: 'Fashion'
    },
    {
        product_id: 5049287502039485,
        companyName: 'Adventure Seekers',
        productName: 'Rock Climbing Shoes - SummitClimb',
        summary: 'Specialized rock climbing shoes for vertical challenges',
        description: "Conquer the heights with the SummitClimb rock climbing shoes. Designed for precision and grip, these shoes feature a snug fit and sticky rubber outsole, perfect for gripping onto even the smallest holds. Whether you're bouldering or tackling a climbing route, these shoes are your ultimate partner.",
        price: '$79.95',
        discountRate: '20%',
        oldPrice: '$99.99',
        src: './images/shoes/images_16.jpeg',
        collection: 'Unisex',
        category: 'Outdoor'
    },
    {
        product_id: 7283939485792038,
        companyName: 'Casual Comfort',
        productName: 'Slip-On Sneakers - Everyday Ease',
        summary: 'Comfortable slip-on sneakers for daily wear',
        description: 'Experience the ease of the Everyday Ease slip-on sneakers. These sneakers offer a casual and relaxed style, perfect for everyday activities. The elasticated panels ensure a secure fit, and the cushioned insole provides all-day comfort. From running errands to casual outings, these sneakers have you covered.',
        price: '$49.99',
        discountRate: '0%',
        oldPrice: '$49.99',
        src: './images/shoes/images_15.jpeg',
        collection: 'Unisex',
        category: 'Casual'
    },
    {
        product_id: 3948502957029374,
        companyName: 'Pro Runners',
        productName: 'Marathon Running Shoes - EndurancePlus',
        summary: 'High-performance marathon running shoes for endurance',
        description: 'Go the distance with the EndurancePlus marathon running shoes. Engineered for long-distance runners, these shoes combine lightweight construction with responsive cushioning. The breathable upper keeps your feet cool as you tackle the miles. Step into these shoes and prepare for your next marathon.',
        price: '$129.99',
        discountRate: '15%',
        oldPrice: '$152.99',
        src: './images/shoes/images_10.jpeg',
        collection: 'Unisex',
        category: 'Sport'
    },
    {
        product_id: 5029837562847503,
        companyName: 'Trendsetters',
        productName: 'Slingback Sandals - Urban Chic',
        summary: 'Chic slingback sandals for a stylish urban look',
        description: "Make a statement with the Urban Chic slingback sandals. These sandals feature a sleek slingback design with a modern twist. The versatile style pairs well with both casual and dressy outfits. Whether you're exploring the city or enjoying a night out, these sandals add a touch of urban flair.",
        price: '$59.99',
        discountRate: '10%',
        oldPrice: '$66.99',
        src: './images/shoes/zed.png',
        collection: 'Women',
        category: 'Fashion'
    },
    {
        product_id: 8779626812000902000,
        companyName: 'Active Performance',
        productName: 'Running Shoes - SwiftStride',
        summary: 'Versatile running shoes for various activities',
        description: "Stay active with the SwiftStride running shoes. These shoes are designed to provide comfort and support during your runs, walks, or workouts. The breathable upper keeps your feet cool, while the cushioned sole absorbs impact. Whether you're a seasoned runner or just starting your fitness journey, these shoes have you covered.",
        price: '$69.99',
        discountRate: '20%',
        oldPrice: '$87.99',
        src: './images/shoes/images_7.jpeg',
        collection: 'Unisex',
        category: 'Sport'
    },
    {
        product_id: 7779548098937489000,
        companyName: 'Casual Comfort',
        productName: 'Slip-On Loafers - Relaxed Steps',
        summary: 'Casual slip-on loafers for everyday comfort',
        description: "Experience the laid-back comfort of the Relaxed Steps slip-on loafers. These loafers offer a relaxed and effortless style, perfect for casual occasions. The soft and flexible design ensures a comfortable fit, and the textured sole provides traction. Whether you're heading to work or running errands, these loafers are a versatile choice.",
        price: '$42.99',
        discountRate: '0%',
        oldPrice: '$42.99',
        src: './images/shoes/images_20.jpeg',
        collection: 'Unisex',
        category: 'Casual'
    },
    {
        product_id: 5737696536973598000,
        companyName: 'Fashion Fusion',
        productName: 'Ankle Boots - Urban Edge',
        summary: 'Stylish ankle boots for a modern urban look',
        description: "Elevate your style with the Urban Edge ankle boots. These boots feature a sleek and contemporary design, perfect for adding a fashionable touch to your outfit. The chunky heel provides stability, while the zip closure ensures easy on and off. Whether you're hitting the city streets or attending a trendy event, these boots make a statement.",
        price: '$79.95',
        discountRate: '10%',
        oldPrice: '$89.99',
        src: './images/shoes/black_heel.png',
        collection: 'Women',
        category: 'Fashion'
    },
    {
        product_id: 2772049993442948600,
        companyName: 'Adventure Seekers',
        productName: 'Waterproof Hiking Boots - Trailblaze',
        summary: 'Durable waterproof hiking boots for outdoor exploration',
        description: 'Embark on your outdoor adventures with confidence in the Trailblaze waterproof hiking boots. These boots are built to withstand various terrains and weather conditions. The waterproof construction keeps your feet dry, while the rugged outsole provides traction on slippery surfaces. Lace up these boots and blaze your own trail.',
        price: '$94.99',
        discountRate: '15%',
        oldPrice: '$111.99',
        src: './images/shoes/images_14.jpeg',
        collection: 'Men',
        category: 'Outdoor'
    },
    {
        product_id: 3238889607572470300,
        companyName: 'Trendsetters',
        productName: 'Chunky Sneakers - Retro Vibes',
        summary: 'Retro-style chunky sneakers for a nostalgic look',
        description: "Embrace the retro trend with the Retro Vibes chunky sneakers. These sneakers feature a chunky sole and bold colors, reminiscent of the '90s era. The padded collar and cushioned insole provide comfort, while the eye-catching design adds a playful touch to your outfit. Step into the past with these nostalgic sneakers.",
        price: '$59.99',
        discountRate: '0%',
        oldPrice: '$59.99',
        src: './images/shoes/images_13.jpeg',
        collection: 'Men',
        category: 'Fashion'
    },
    {
        product_id: 5361848610335189000,
        companyName: 'Pro Athletes',
        productName: 'Cross Training Shoes - PowerFlex',
        summary: 'High-performance cross training shoes for versatile workouts',
        description: 'Enhance your training sessions with the PowerFlex cross training shoes. Designed for versatility, these shoes provide stability and support for a variety of exercises. The durable construction and flexible sole make them suitable for weightlifting, cardio, and more. Maximize your performance with these all-around training shoes.',
        price: '$79.95',
        discountRate: '20%',
        oldPrice: '$99.99',
        src: './images/shoes/images_17.jpeg',
        collection: 'Men',
        category: 'Outdoor'
    },
    {
        product_id: 7036687655104650000,
        companyName: 'Elegant Attire',
        productName: 'Evening Pumps - GlamourNights',
        summary: 'Sophisticated evening pumps for formal occasions',
        description: 'Make a statement at formal events with the GlamourNights evening pumps. These pumps feature an elegant design with a pointed toe and stiletto heel. The luxurious materials and detailed craftsmanship add a touch of sophistication to your ensemble. Step into these pumps and exude timeless elegance.',
        price: '$89.99',
        discountRate: '10%',
        oldPrice: '$99.99',
        src: './images/shoes/zara.png',
        collection: 'Women',
        category: 'Fashion'
    },
    {
        product_id: 2472888241437052400,
        companyName: 'Outdoor Explorers',
        productName: 'Sandals - Nature Trek',
        summary: 'Comfortable sandals for outdoor enthusiasts',
        description: "Embrace the great outdoors with the Nature Trek sandals. These sandals combine comfort and functionality, making them ideal for nature enthusiasts. The adjustable straps provide a customizable fit, and the cushioned footbed ensures comfort during long walks. Whether you're hiking or exploring, these sandals are your go-to choice.",
        price: '$49.95',
        discountRate: '0%',
        oldPrice: '$49.95',
        src: './images/shoes/shoe_blend.jpg',
        collection: 'Unisex',
        category: 'Outdoor'
    },
    {
        product_id: 3874038347299851000,
        companyName: 'Sports Elegance',
        productName: 'Golf Shoes - SwingMaster',
        summary: 'Stylish golf shoes for a day on the green',
        description: 'Elevate your golf game with the SwingMaster golf shoes. These shoes blend style and performance, providing stability and traction on the golf course. The sleek design features classic details and modern enhancements, making them suitable for both casual and competitive rounds. Step up your golfing experience with these shoes.',
        price: '$99.99',
        discountRate: '15%',
        oldPrice: '$117.99',
        src: './images/shoes/shoe_blend2.jpg',
        collection: 'Unisex',
        category: 'Sport'
    }
];

